local cfg = {}

cfg.Icon = {
    [1] = {--矿工
        icon = "ui://Game375/symbol_kg",
        zorder = 50,
        topzorder = 50,
        isplist = false,
        Scale = vec2(1,1),
        Pos = vec2(64,58),
        animation_n = "normal",
    },
    [2] = {--驴
        icon = "ui://Game375/symbol_l",
        zorder = 40,
        topzorder = 40,
        isplist = false,
        Scale = vec2(1,1),
        Pos = vec2(64,58),
        animation_n = "normal",
    },
    [3] = {--矿车
        icon = "ui://Game375/symbol_kc",
        zorder = 30,
        topzorder = 30,
        isplist = false,
        Scale = vec2(1,1),
        Pos = vec2(64,58),
        animation_n = "normal",
    },
    [4] = {--头盔
        icon = "ui://Game375/symbol_tk",
        zorder = 20,
        topzorder = 20,
        isplist = false,
        Scale = vec2(1,1),
        Pos = vec2(64,58),
        animation_n = "normal",
    },
    [5] = {--工具
        icon = "ui://Game375/symbol_gj",
        zorder = 30,
        topzorder = 30,
        isplist = false,
        Scale = vec2(1,1),
        Pos = vec2(64,58),
        animation_n = "normal",
    },
    [6] = {--A
        icon = "ui://Game375/symbol_a",
        zorder = 20,
        topzorder = 20,
        isplist = false,
        Scale = vec2(1,1),
        Pos = vec2(64,58),
        animation_n = "normal",
    },
    [7] = {--K
        icon = "ui://Game375/symbol_k",
        zorder = 10,
        topzorder = 10,
        isplist = false,
        Scale = vec2(1,1),
        Pos = vec2(64,58),
        animation_n = "normal",
    },
    [8] = {--Q
        icon = "ui://Game375/symbol_q",
        zorder = 1,
        topzorder = 1,
        isplist = false,
        Scale = vec2(1,1),
        Pos = vec2(64,58),
        animation_n = "normal",
    },
    [9] = {--J
        icon = "ui://Game375/symbol_j",
        zorder = 1,
        topzorder = 1,
        isplist = false,
        Scale = vec2(1,1),
        Pos = vec2(64,58),
        animation_n = "normal",
    },
    [10] = {--雷管蓝布(落地牌)
        icon = "ui://Game375/symbol_bouns_lan",
        zorder = 80,
        topzorder = 80,
        isplist = false,
        Scale = vec2(0.437,0.437),
        Pos = vec2(65,62),
        node_name = "lan_bouns_anim",
        animations = {come = "bouns_lan_come",loop = "bouns_lan_loop",win = "bouns_lan_win"}
    },
    [11] = {--wild：金块
        icon = "ui://Game375/symbol_jk",
        zorder = 60,
        topzorder = 60,
        isplist = false,
        Scale = vec2(1.17,1.17),
        Pos = vec2(64,58),
        animation = "wild_win",
    },
    [12] = {--SC：矿洞
        icon = "ui://Game375/symbol_kd",
        zorder = 70,
        topzorder = 70,
        isplist = false,
        Scale = vec2(0.438,0.44),
        Pos = vec2(63,55),
        animation = "sc_win",
    },
    [13] = {--雷管紫布x7(落地牌)
        icon = "ui://Game375/symbol_bouns_zi",
        zorder = 90,
        topzorder = 90,
        isplist = false,
        Scale = vec2(0.403,0.401),
        Pos = vec2(64,58),
        node_name = "zi_bouns_anim",
        animations = {loop = "bouns_zi_loop",win = "bouns_zi_win"},
    },
    [14] = {--雷管绿布双倍(落地牌)
        icon = "ui://Game375/symbol_bouns_lv",
        zorder = 100,
        topzorder = 100,
        isplist = false,
        Scale = vec2(0.405,0.4),
        Pos = vec2(70,58),
        node_name = "lv_bouns_anim",
        animations = {loop = "bouns_lv_loop",win = "bouns_lv_win"},
    },
}

return cfg

