
-- UI事件订阅键值
FGUIEventKey = {
	onChanged          = "onChanged"         ,
	onSubmit           = "onSubmit"          ,
	onTouchBegin       = "onTouchBegin"      ,
	onTouchMove        = "onTouchMove"       ,
	onTouchEnd         = "onTouchEnd"        ,
	onClick            = "onClick"           ,
	onRollOver         = "onRollOver"        ,
	onRollOut          = "onRollOut"         ,
	onMouseWheel       = "onMouseWheel"      ,
	onRightClick       = "onRightClick"      ,
	onMiddleClick      = "onMiddleClick"     ,
	onPositionChanged  = "onPositionChanged" ,
	onSizeChanged      = "onSizeChanged"     ,
	onKeyDown          = "onKeyDown"         ,
	onScroll           = "onScroll"          ,
	onScrollEnd        = "onScrollEnd"       ,
	onPullDownRelease  = "onPullDownRelease" ,
	onPullUpRelease    = "onPullUpRelease"   ,
	onClickItem        = "onClickItem"       ,
	onClickLink        = "onClickLink"       ,
	onRightClickItem   = "onRightClickItem"  ,
	onDragStart        = "onDragStart"       ,
	onDragMove         = "onDragMove"        ,
	onDragEnd          = "onDragEnd"         ,
	onDrop             = "onDrop"            ,
	onGearStop         = "onGearStop"        ,
	onInit         	   = "onInit"            ,
	onShown            = "onShown"           ,
	onHide             = "onHide"            ,
	doShowAnimation	   = "doShowAnimation"   ,
	doHideAnimation	   = "doHideAnimation"   ,
}
