// ==============================================
// 📄 Source: 257_Slots_Client.proto
package PB.Slots_Client;

message DuanWuNormalRet {
    optional NormalSpin normalSpin = 1;
}

message DuanWuFreeRet {
    optional FreeSpin freeSpin = 1;
}

message DuanWuEnterResumed {
    optional Enter_Success enterBase = 1;
    optional int64 currentWinCoin = 2;
    optional int64 currentBetMoney = 3;
    optional DuanWuNormalRet resumedNormal = 4;
    optional DuanWuFreeRet resumedFree = 5;
    optional int32 type = 6;
    repeated int32 cells = 7;
    optional int32 lvID = 8;
}
