// ==============================================
// 📄 Source: 271_Slots_Client.proto
package PB.Slots_Client;

message DragonKingNormalRet {
    optional NormalSpin normalSpin = 1;
}

message DragonKingFreeRet {
    optional FreeSpin freeSpin = 1;
}

message DragonKingFreeTypeRet {
    optional FreeType freeType = 1;
}

message DragonKingEnterResumed {
    optional Enter_Success enterBase = 1;
    optional int64 currentWinCoin = 2;
    optional int64 currentBetMoney = 3;
    optional DragonKingNormalRet resumedNormal = 4;
    optional DragonKingFreeRet resumedFree = 5;
    optional DragonKingFreeTypeRet freeType = 6;
    optional int32 freetime = 7;
    optional int32 type = 8;
    repeated int32 cells = 9;
    optional int32 lvID = 10;
}
