// ==============================================
// 📄 Source: 273_koiAnnunciation.proto
package PB.koiAnnunciation;

message Cell {
    optional int32 index = 1;
    optional int32 icon = 2;
}

message Line {
    optional int32 lineIndex = 1;
    optional int64 winCoin = 2;
    optional int32 icon = 3;
    repeated Cell lineCells = 4;
}

message NormalSpin {
    optional int64 bet = 1;
    optional int64 winCoin = 2;
    repeated Cell grids = 3;
    optional int32 intoFree = 4;
    repeated Line lines = 5;
    optional SlotMoneyGift slotMoneyGift = 6;
    optional SlotMoney slotMoney = 7;
    optional int64 levelUpMoney = 8;
    repeated int64 levelUpMoneys = 9;
    optional int32 intoCollect = 10;
    optional int32 lockStates = 11;
}

message FreeType {
    optional int32 type = 1;
}

message FreeSpin {
    optional int64 bet = 1;
    optional int64 winCoin = 2;
    repeated Cell grids = 3;
    optional int32 wildBet = 4;
    optional int64 bonusWinCoin = 5;
    optional int32 allCount = 6;
    optional int32 totalCount = 7;
    optional int32 newFreeTime = 8;
    optional int32 addTime = 9;
    repeated Line lines = 10;
    optional SlotMoneyGift slotMoneyGift = 11;
    optional SlotMoney slotMoney = 12;
    optional int32 intoCollect = 13;
    optional int32 lockStates = 14;
}
