// ==============================================
// 📄 Source: 276_Slots_Client.proto
package PB.Slots_Client;

message WealthTreasureNormalRet {
    optional NormalSpin normalSpin = 1;
}

message WealthTreasureFreeRet {
    optional FreeSpin freeSpin = 1;
}

message WealthTreasureEnterResumed {
    optional Enter_Success enterBase = 1;
    optional int64 currentWinCoin = 2;
    optional int64 currentBetMoney = 3;
    optional WealthTreasureNormalRet resumedNormal = 4;
    optional WealthTreasureFreeRet resumedFree = 5;
    optional int32 type = 7;
    repeated int32 cells = 9;
    optional int32 lvID = 10;
}
