// ==============================================
// 📄 Source: 278_richFish.proto
package PB.RichFish;

message Cell {
    optional int32 index = 1;
    optional int32 icon = 2;
    optional int32 type = 3;
    optional int64 wildValue = 4;
    optional int64 wildValue2 = 5;
}

message Line {
    optional int32 lineIndex = 1;
    optional int64 winCoin = 2;
    optional int32 icon = 3;
    repeated Cell lineCells = 4;
}

message NormalSpin {
    optional int64 bet = 1;
    optional int64 winCoin = 2;
    repeated Cell grids = 3;
    optional int32 intoFree = 5;
    optional int32 FreeTime = 6;
    repeated Line lines = 7;
    optional SlotMoneyGift slotMoneyGift = 9;
    optional SlotMoney slotMoney = 10;
    optional int64 levelUpMoney = 11;
    repeated int64 levelUpMoneys = 12;
}

message FreeSpin {
    optional int64 bet = 1;
    optional int64 winCoin = 2;
    repeated Cell grids = 3;
    optional int64 bonusWinCoin = 5;
    optional int32 allCount = 6;
    optional int32 totalCount = 7;
    optional int32 newFree = 8;
    repeated Line lines = 9;
    optional int32 freeType = 4;
    optional int32 freeA = 10;
    optional int32 freeB = 11;
    optional int32 freeC = 12;
    optional SlotMoneyGift slotMoneyGift = 13;
    optional SlotMoney slotMoney = 14;
}
