// ==============================================
// 📄 Source: 310_treeWealth.proto
package PB.TreeWealth;

message Cell {
    optional int32 index = 1;
    optional int32 icon = 2;
    optional int32 type = 3;
}

message Line {
    optional int32 lineIndex = 1;
    optional int64 winCoin = 2;
    optional int32 icon = 3;
    repeated Cell lineCells = 4;
}

message NormalSpin {
    optional int64 bet = 1;
    optional int64 winCoin = 2;
    repeated Cell grids = 3;
    optional int32 intoFree = 4;
    optional int32 FreeTime = 5;
    repeated Line lines = 6;
    optional int32 intoCollect = 7;
    optional int32 lockStates = 8;
    optional SlotMoneyGift slotMoneyGift = 9;
    optional SlotMoney slotMoney = 10;
    optional int64 levelUpMoney = 11;
    repeated int64 levelUpMoneys = 12;
}

message FreeType {
    optional int32 type = 1;
}

message FreeSpin {
    optional int64 bet = 1;
    optional int64 winCoin = 2;
    repeated Cell grids = 3;
    optional int64 bonusWinCoin = 4;
    optional int32 allCount = 5;
    optional int32 totalCount = 6;
    optional int32 newFreeTime = 7;
    repeated Line lines = 8;
    optional int32 isShowbig = 9;
    optional int32 intoCollect = 10;
    optional int32 lockStates = 11;
    optional SlotMoneyGift slotMoneyGift = 12;
    optional SlotMoney slotMoney = 13;
}
