// ==============================================
// 📄 Source: 310_Slots_Client.proto
package PB.Slots_Client;

message TreeWealthNormalRet {
    optional NormalSpin normalSpin = 1;
}

message TreeWealthFreeRetType {
    optional FreeType freeType = 1;
}

message TreeWealthFreeRet {
    optional FreeSpin freeSpin = 1;
}

message TreeWealthEnterResumed {
    optional Enter_Success enterBase = 1;
    optional int64 currentWinCoin = 2;
    optional int64 currentBetMoney = 3;
    optional TreeWealthNormalRet resumedNormal = 4;
    optional TreeWealthFreeRet resumedFree = 5;
    optional TreeWealthFreeRetType freeType = 6;
    optional int32 type = 7;
    repeated int32 cells = 9;
    optional int32 lvID = 10;
}
