// ==============================================
// 📄 Source: 353_Buffalo.proto
package PB.Buffalo;

message Cell {
    optional int32 index = 1;
    optional int32 icon = 2;
    optional int32 SymbolType = 3;
    optional int64 SymbolValue = 4;
    optional int32 IsHide = 5;
}

message Line {
    optional int32 lineIndex = 1;
    optional int64 winCoin = 2;
    optional int32 icon = 3;
    repeated Cell lineCells = 4;
}

message NormalSpin {
    optional int64 bet = 1;
    optional int64 winCoin = 2;
    repeated Cell grids = 3;
    optional int32 intoFree = 4;
    repeated Line lines = 6;
    optional SlotMoneyGift slotMoneyGift = 7;
    optional SlotMoney slotMoney = 8;
    optional int64 levelUpMoney = 9;
    repeated int64 levelUpMoneys = 10;
}

message FreeType {
    optional int32 type = 1;
}

message FreeSpin {
    optional int64 bet = 1;
    optional int64 winCoin = 2;
    repeated Cell grids = 3;
    optional int32 wildType = 15;
    optional int64 bonusWinCoin = 4;
    optional int32 allCount = 5;
    optional int32 totalCount = 6;
    repeated Line lines = 7;
    optional int32 addTime = 8;
    optional int32 gametype = 9;
    optional SlotMoneyGift slotMoneyGift = 11;
    optional SlotMoney slotMoney = 12;
}
