// ==============================================
// 📄 Source: 367_TheGreatImmortals.proto
package PB.TheGreatImmortals;

message Cell {
    optional int32 index = 1;
    optional int32 icon = 2;
}

message JackPot {
    optional int32 index = 1;
    optional int32 spType = 2;
    optional int64 money = 3;
}

message Line {
    optional int32 lineIndex = 1;
    optional int64 winCoin = 2;
    optional int32 icon = 3;
    repeated Cell lineCells = 4;
    repeated JackPot lineJackPots = 5;
}

message NormalSpin {
    optional int64 bet = 1;
    optional int64 winCoin = 2;
    repeated Cell grids = 3;
    repeated Line lines = 4;
    optional int32 intoFree = 5;
    optional int32 intoSpec = 6;
    optional int32 specTime = 7;
    optional int32 freeTime = 8;
    optional int32 lockStates = 9;
    optional SlotMoneyGift slotMoneyGift = 10;
    optional SlotMoney slotMoney = 11;
    optional int64 levelUpMoney = 12;
    repeated int64 levelUpMoneys = 13;
}

message FreeSpin {
    optional int64 bet = 1;
    optional int64 winCoin = 2;
    repeated Cell grids = 3;
    repeated Line lines = 4;
    optional int32 freeTime = 5;
    optional int32 totalFreeTime = 6;
    optional SlotMoneyGift slotMoneyGift = 7;
    optional SlotMoney slotMoney = 8;
}

message SpecSpin {
    optional int64 bet = 1;
    optional int64 winCoin = 2;
    repeated Cell grids = 3;
    repeated Line lines = 4;
    optional int32 specTime = 5;
    optional SlotMoneyGift slotMoneyGift = 6;
    optional SlotMoney slotMoney = 7;
}
