// ==============================================
// 📄 Source: 441_Slots_Client.proto
package PB.Slots_Client;

message WesternCashNormalRet {
    optional NormalSpin normalSpin = 1;
}

message WesternCashFreeRet {
    optional FreeSpin freeSpin = 1;
}

message WesternCashSpecRet {
    optional SpecSpin specSpin = 1;
}

message WesternCashEnterResumed {
    optional int32 lvID = 1;
    optional int64 currentWinCoin = 2;
    optional int64 currentBetMoney = 3;
    optional Enter_Success enterBase = 4;
    optional WesternCashNormalRet resumedNormal = 5;
    optional WesternCashFreeRet resumedFree = 6;
    optional WesternCashSpecRet resumedSpec = 7;
    optional int32 status = 8;
    repeated int32 cells = 9;
}
