// ==============================================
// 📄 Source: 485_Slots_Client.proto
package PB.Slots_Client;

message FireLinkNormalRet {
    optional NormalSpin normalSpin = 1;
}

message FireLinkFreeRet {
    optional FreeSpin freeSpin = 1;
}

message FireLinkSpecialRet {
    optional SpecialSpin specialSpin = 1;
}

message FireLinkSelectRet {
    optional SelectType selectType = 1;
}

message FireLinkEnterResumed {
    optional int32 lvID = 1;
    optional int64 currentBetMoney = 2;
    optional Enter_Success enterBase = 3;
    optional FireLinkNormalRet resumedNormal = 4;
    optional FireLinkFreeRet resumedFree = 5;
    optional FireLinkSpecialRet resumedSpecial = 6;
    optional FireLinkSelectRet resumedSelect = 7;
    optional int32 lastMsgType = 8;
}
