---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by F.
--- DateTime: 2023/11/10 17:43
---

local cls = Class("debugCls")

function cls:ctor()
    self.debug_fun = {}
    FSysEventEmitter:AddListener('RECEIVE_CONSOLE_COMMAND', function(data)
        self:execute(data.command, data.args)
    end, self)
end

function cls:execute(cmd, args)
    if cmd == "help" then
        print('debug', " Found usable commands")
        for k, v in pairs(self.debug_fun) do
            print('debug', " ---->", k, v.label)
        end
    else
        if not self.debug_fun[cmd] then
            print("not find execute function")
        else
            if #args == 0 then
                self.debug_fun[cmd].func()
            else
                self.debug_fun[cmd].func(table.unpack(args))
            end
        end
    end
end

---@public
---@param command string 命令
---@param label string  说明
---@param callback function(...):void 执行的方法
function cls:addExecute(command, label, callback)
    self.debug_fun[command] = {
        func = callback,
        label = label,
    }
end

function cls:__delete()
    FSysEventEmitter:RemoveListenersByTag(self)
end

return cls
